<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <b style="color: rgb(242 ,242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font face="Verdana" size="2">Olumlu Özellikleri:</font></b><font face="Verdana" style="color: rgb(242 ,242, 242); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font size="2"><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Alçak gönüllü. Şefkatli. Sempatik. Hassas. Adapte olabilir. Etkili. Anlayışlı. Nazik. Sezgili. Renkli hayaller. Derin duygular. Sevgiye düşkünlük. Merhametli. Güzel sanatlarda başarılı. İyi 
    niyetli. Yardımsever.</font><br />
    <br />
    </font><b><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font size="2"><b>Olumsuz Özellikleri:</b><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Belirsizlik. İhmalcilik. Gizlilik. Kolay dağılmak. Zayıf arzular. Kararsızlık. Mücadeleci değil. Karamsar. Çekingen. Alıngan</font></font></font><p style="color: rgb(242 ,242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font face="Verdana" size="2"><b>Balık Takım Yıldızı (Astronomi)</b><br />
        <font color="#ffffff">Balık takımyıldızının ilk dekanındaki yıldız grubu Band olarak bilinir. İkinci dekan, güçlü bir ifade ile oturarak, bir elinde bir krallık asası tutan, diğer eliyle de Band&#39;ı yakalamış olan Cepheus&#39;tur. Cepheus&#39;un sağ omuzundaki yıldız Al Deramin, kuşağındaki Al Phirk, sol dizindeki ise Shepherd yani Çoban Yıldızı yeralır. Kuzeyde son dekanatta ise kırılmış zincirleriyle, güzel Andromeda bulunur.</font></font></p>
    <b style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font color="#27373f" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" style="color: rgb(0, 0, 0); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><b><font color="#800000" size="2">Balık Burcu Kadını Genel Özellikleri</font></b></font><p style="color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Balık burcu kadını hırslı,tuttuğunu koparan, çekici, sempatik ve iyi huylu tavırlarıyla dikkati çeker. Duygusal ve romantiktir. Evcimen ve evine bağlı bir yapısı vardır. Kendini evinde huzurlu ve rahat hisseder.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Balık burcu kadınının sezgileri kuvvetlidir. Güzel olan her şeyi sever ve rahatına fazlasıyla düşkündür. Toplum içinde dikkati çekmek ister ve kendiyle gurur duyar.İnce ruhludur ve sanata düşkündür.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Kıskanç bir yapısı vardır ve her konuda en iyi olmak ister. İstediği her şeye ulaşmak ister ve bunun için elinden gelen çabayı gösterir. Toplum içinde neşeli ve hareketli tavırlarıyla dikkati çeker. Giyime ve kuşama , bakımlı olmaya önem verir.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        <br />
        </font><b><font color="#27373f" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana"><b><font color="#800000" size="2">Balık Burcu Erkeği Genel Özellikleri</font></b></font></p>
    <p style="color: rgb(242 ,242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Balık burcu erkeği nazik, uyumlu,iyimser ve hayalperest yapısıyla dikkati çeker. Umursamaz tavırları olaylardan fazla etkilenmemesine neden olur. Düzenden ve sorumluluk almaktan hoşlanmaz. Başına buyruk yaşamaktan keyif alır.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Balık burcu erkeği iş konusunda pratikliği sayesinde başarılı olur. Art niyetli değildir. İnsanlara kolayca güvenir.<span class="Apple-converted-space">&nbsp;</span></font></p>
</asp:Content>

