<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <font face="Verdana" style="color: rgb(242, 242, 242); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; "><b><font color="#27373f" size="2"><span class="Apple-converted-space">&nbsp;</span></font><font size="2"><br />
    Olumlu Özellikleri:</font></b><font size="2"><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Analizcilik. Dostluk. Dikkat. Ustalık. Cana yakınlık. Temizlik. Titizlik. Alçak gönüllülük. Giyim merakı. Hesap kafası. Esprili konuşma. İyilik isteği.</font><br />
    <br />
    </font><b><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font size="2"><b>Olumsuz Özellikleri:</b><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Hastalık hastası. İşgüzar. Aceleci. Aşırı tenkitçi. Aşırı titiz. Kolay beğenmez. Geleneklere sıkı bağlı. Aşırı meraklı</font></font></font><p style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; ">
        <font face="Verdana" size="2"><b>Başak Takım Yıldızı (Astronomi)</b><br />
        <font color="#ffffff">Başak takımyıldızının ilk dekanatında Coma, ikincisinde başlıca yıldızları Bungula ve Aguna olan Centaurus bulunur. Üçüncü dekanatta, ekliptiğe daha yakın bir yerde ise Caphir ve Spica yani Tohum yer alır.</font></font></p>
    <font face="Verdana" style="color: rgb(242, 242, 242); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; "><b><font color="#800000" size="2"><span class="Apple-converted-space">&nbsp;</span>Başak Burcu Kadını Genel Özellikleri</font></b></font><p style="color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; ">
        <font color="#ffffff" face="Verdana" size="2">Başak burcu kadını sorumluluk sahibi, idealist, hırslı, nazik, detaycı ve hassastır. Titizdir ve en ufak ayrıntılara dikkat eden yapısıyla dikkat çeker. Evcimen yapısıyla evine çocuklarına çok düşkündür. Evine vakit ayırmaktan fazlasıyla keyif alır.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Başak burcu kadını hoş mizacıyla dostları tarafından sevilir ve çok sayıda arkadaşı vardır. Mizah anlayışı oldukça gelişmiştir.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Başak burcu kadını çalışkan ve azimlidir. Sorumluluklarını sonuna kadar yerine getirir. Başarmak için elinden gelen tüm çabayı gösterir. Pratik olması nedeniyle olaylara anında müdahale edebilmektedir. Diğer bir taraftan alıngan bir yapısı vardır.Kolayca incinebilir ve darıldığı kişiyi hemen affedemez. Kindar değildir fakat hemen de unutamaz.<br />
        </font>
    </p>
    <p align="left" style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; ">
        <b><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana"><b><font color="#800000" size="2">Başak Burcu Erkeği Genel Özellikleri</font></b></font></p>
    <p align="left" style="color: rgb(242, 242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Başak burcu erkeği inatçı, titiz,detaycı ve mantıklı yapısıyla dikkat çeker. Hoş ve sevecen bir mizacı vardır. Daima bakımlı ve hoş görünmeye dikkat eder. Hırslı ve çalışkandır. Para konusunda tutumludur.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Başak burcu erkeği çevresindeki olumsuzlukları sözünü sakınmadan tenkit edebilir. Eleştirmeyi sever. Fazlasıyla açık sözlüdür. Düşünceli olmasına rağmen hoşuna gitmeyen şeyleri direkt ve net olarak söyler ve kırıcı olabilir. Temizlik onun için çok önemlidir. Bazen aşırıya kaçacak derecede titiz olabilir.<span class="Apple-converted-space">&nbsp;</span></font></p>
</asp:Content>

