<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <font face="Verdana" size="2" style="color: rgb(242, 242 ,242); font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(242, 242, 242);">
    <br />
    </font><b style="color: rgb(242 ,242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(242, 242, 242);"><font color="#ffffff" face="Verdana" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" style="color: rgb(242 ,242 ,242); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; "><b><font size="2"><br />
    Olumlu Yanları:</font></b><font size="2"><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Sırdaş. Duygularım belli etmez. Gerçek dost. Cazibeli. Güçlü. Seks sembolü. Çalışkan. Kararlı. Unutmaz. Güçlü sezgiler. Güçlü duygular. Yüksek imajinasyon. Anlayışlı. Dikkatli. Yüksek analiz gücüne sahip. Sevgi. Pişmanlık.</font><br />
    <br />
    </font></font><b style="color: rgb(242, 242, 242; font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(242, 242, 242);"><font color="#ffffff" face="Verdana" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" size="2" style="color: rgb(242, 242 ,242); font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><b><br />
    Olumsuz Yanları:</b><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Kindar. Kuşkucu. Kıskanç. alıngan. Dik kafalı. Suskun. Akrep gibi, zehirleyici. Alaycı. Ben merkezci. İhtiraslı</font></font><p style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; ">
        <font face="Verdana" size="2"><b>Akrep Takım Yıldızı (Astronomi)</b><br />
        <font color="#ffffff">Akrep takımyıldızının en üstünde, üç dekanı da kapsayacak şekilde, Zodyak&#39;ın dışında Ophiuchus-Yılancı, onun üzerinde Hercules ve Cerberus-Cehennemin Üç Başlı Köpeği yer alır. Bunların hepsinin altında Akrep takımyıldızı bulunur. Hercules yıldız kümesindeki en parlak yıldız, Ras el Gethi&#39;dir.<br />
        &nbsp;</font></font></p>
    <b style="color: rgb(242 ,242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font color="#27373f" face="Verdana" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" style="color: rgb(255,255,255); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; "><b><font color="#800000" size="2">Akrep Burcu Kadını Genel Özellikleri</font></b></font><p style="color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Kıskançlık akrep burcu kadınının mizacında vardır. Kendisinden üstün olan ya da sahip olamadığı her şeyi kıskanabilir. Dostlukları onun için çok önemlidir. Daima çevresinde nüfuzlu dostları bulunur.Yalandan nefret eder. Yalan söylenildiğini hissettiği anda o ortamdan uzaklaşmayı tercih eder. Dürüsttür ve dürüstlüğe fazlasıyla önem verir.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Gururlu akrep burcu kadını doğru bildiği konularda kesinlikle taviz vermez.Cesurdur ve tuttuğunu koparıncaya kadar çabalamaya devam eder. Başarısızlığı hiçbir şekilde kabul etmez. En olumsuz yönü şüpheci olmasıdır. Herkese karşı garip bir şüphecilikle yaklaşır. Kolay kolay karşı tarafa güvenmez. Her ne kadar mantığıyla hareket etse de içten içe fazlasıyla duygusaldır.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Akrep burcu kadını yapılan iyiliği de kötülüğü de unutmaz. İntikam duygusu çok gelişmiştir. Çevresindeki kötü niyetli insanlara karşı suskun kalmayı pek tercih etmez.<span class="Apple-converted-space">&nbsp;</span></font></p>
    <p style="color: rgb(242 ,242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <b><font color="#27373f" face="Verdana" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana"><b><font color="#800000" size="2">Akrep Burcu Erkeği Genel Özellikleri</font></b></font></p>
    <p style="color: rgb(242, 242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Akrep burcu erkeği herkese ve her şeye karşı şüpheci tavırlar içindedir. Kimseye kolay kolay güvenmez. Maddiyata çok fazla önem verir. Çünkü maddi anlamda edinilen gücün güven verdiğini düşünür.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Eleştirmeyi seven akrep burcu erkeği tenkit edilmekten hoşlanmaz. Açık sözlü ve güvenilirdir. Dostlarına çok önem verir.Fedakardır.<span class="Apple-converted-space">&nbsp;</span></font></p>
</asp:Content>

