<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <b style="color: rgb(242, 242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font face="Verdana" size="2">Olumlu Yanları:</font></b><font face="Verdana" size="2" style="color: rgb(242 ,242, 242); font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Öncülük ve macera ruhu. Girişkenlik. Adam yönlendirme. Hedef belirleme özelliği. Yüksek Enerji. Engelleri aşabilme yetişi. Sınırlamalardan nefret. Liderlik. Dürüstlük. Hazır cevaplık. Canlılık.</font></font><p style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font face="Verdana"><b><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font><font size="2">Olumsuz Yanları:</font></b><font size="2"><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Egoizm. Kararları yıkmak. Kendini öne sürmek, ileri-ye çıkartmak. Alaycı, isyankar. Sabırsız. Saldırgan. Hiddetli. Ani çıkışlar</font></font></font></p>
    <p align="left" style="color: rgb(242 ,242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font face="Verdana" size="2"><b>Koç Takım Yıldızı (Astronomi)</b><br />
        <font color="#ffffff">Koç takım yıldızındaki başlıca yıldızlar, Shedar, Ruckbah ve Dat el Cursa&#39;dır. İlk dekanatta, Cassiopeia, ortada Cetus, sonda ise Perseus yer alır</font>.</font></p>
    <p align="justify" style="color: rgb(242, 242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <b><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana"><b><font color="#800000" size="2">Koç Burcu Kadını Genel Özellikleri</font></b></font></p>
    <p align="left" style="color: rgb(242 ,242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font face="Verdana" size="2"><font color="#ffffff">Koç burcu kadını hareketli, konuşkan ve girişimci yapısıyla dikkat çeker. Oldukça da esprilidir. Alımlı, atletik yapılı ve narindir. Eleştirmeyi ve hoşlanmadığı şeyleri mutlaka dile getirir. Toplum içerisinde cazibe ve farklılığıyla dikkat çeker.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Koç kadını iş hayatında oldukça hırslı ve idealisttir. Aklına koyduğunu mutlaka gerçekleştirmek ister ve çizdiği yolda hiç şaşmadan ilerler.Zamanı kullanmayı iyi bilir ve çalışkandır. Koç kadını özellikle içten ve sempatik tavırlarıyla arkadaş çevresinde aranan eğlenceli bir dosttur. İçten içe biraz tedirgin ve huzursuzdur. Kendisini fazlasıyla tenkit eder ve hep bir yarış içerisindeymiş gibi kendiyle çok uğraşır. Dostlarına ve sevdiklerine çok önem verir ve fazlasıyla fedakardır.<span class="Apple-converted-space">&nbsp;</span><br />
        </font></font>
    </p>
    <p align="left" style="color: rgb(242 ,242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        &nbsp;<b><font color="#27373f" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana"><b><font color="#800000" size="2">Koç Burcu Erkeği Genel Özellikleri</font></b></font></p>
    <p align="left" style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Koç burcu erkeği kendine güvenen, hareketli ve enerjik yapısıyla toplum içinde fark edilir. Otoriterdir ve otorite kurmaktan keyif alır. Dik başlıdır ve hata yaptığında bunu kabul etmek istemez ve bencil davranışlar sergiler.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Koç burcu erkeği özgürlüğüne fazlasıyla düşkündür. Dostları ve arkadaşları için yapmayacağı şey yoktur. İnsanlara yardım etmeyi ve onların sorunlarını paylaşmayı sever. Cömerttir ve maddi anlamda da özgür olmayı sever. Kendi işini kurmak ve yürütmek onlar için çok daha caziptir.Başkalarından emir almaktan hoşlanmaz.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Koç burcu erkeği incindiği zaman oldukça kırıcı olur ve sözünü sakınmaz. Tenkitçidir, sert bir dille eleştirebilir. Ev hayatına ve ailesine oldukça düşkündür, fakat dışarıdaki hayatını da fazlasıyla sever. Bu onun yerinde duramayan hareketli yapısından kaynaklanmaktadır. Daima kendini evinde huzurlu ve rahat hissetmek ister.</font></p>
</asp:Content>

