<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <b style="color: rgb(242, 242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font face="Verdana" size="2">
    <br />
    Olumlu Özellikleri:</font></b><font face="Verdana" style="color: rgb(242, 242, 242); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font size="2"><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Hümanist. Bağımsız. Dost. Mucit. Orijinalist. Reformist. Sadık. Vefalı. İdealist. Entelektüel. Yeniliğe meraklı. Değişikliği sever. Geçmişe bağlı.</font><br />
    <br />
    </font><b><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font size="2"><b>Olumsuz Özellikleri:</b><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Umulmadık gariplikler. isyankarlık. Muhalif. Sabit fikirli. Gelenekleri zorlayıcı. Çılgın, tartışmaya meraklı. Dikkati çekmek ister. Çılgın. Kendini beğenmiş. Olmayacak hayaller</font></font></font><p style="color: rgb(242 ,242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font face="Verdana" size="2"><b>Kova Takım Yıldızı (Astronomi)</b><br />
        <font color="#ffffff">Kova takımyıldızının ilk dekanatında Güney Balığı, Pisces Australis, ikinci dekanatta ise sırtındaki dev kanatlarıyla Pegasus vardır. Buradaki başlıca yıldızlar, Markab, Scheat, Enif, Al Genib, Homan, Matar&#39;dır. Üçüncü dekanda güzel bir kuğu bulunur. Yaralı olmasına rağmen Samanyolu&#39;nda daireler çizerek dolaşırken, nebulatik yıldızların tam ortasındadır. Başlıca yıldızları bir haç meydana getirir. En parlak yıldızları, Deneb, Azel, Fafoge, Sadr, Adige ve Arided&#39;dir.</font></font></p>
    <b style="color: rgb(242, 242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" style="color: rgb(242, 242 ,242); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><b><font color="#800000" size="2">Kova Burcu Kadını Genel Özellikleri</font></b></font><p style="color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Kova burcu kadını özgürlüğüne düşkün,kararlı, becerikli ve değişken yapısıyla dikkati çeker. Neşeli ve keyifli bir kişiliği vardır. Çevresinde aranan ve fikrine önem verilen bir dosttur. Dostluğa çok önem verir ve kendi gibi düşünen insanlarla arkadaşlık etmekten çok keyif alır.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Kova burcu kadını kendisini kısıtlayan beraberliklerden uzak durmayı tercih eder.Kişilik olarak zordur. İyi niyetli, kafaca uyuştuğu ve kendisini anlayan bir erkekle mutlu olabilir. Sevdiği zaman mükemmel bir aşık olacak ve ilişkisini keyifli hale getirmek için elinden geleni yapacaktır. Dürüsttür ve güvenilirdir. Çevresindeki insanlara karşı gayet açık ve nettir.<span class="Apple-converted-space">&nbsp;</span></font></p>
    <p style="color: rgb(242 ,242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">
        <br />
        </font><font face="Verdana"><b><font color="#800000" size="2">Kova Burcu Erkeği Genel Özellikleri</font></b></font></p>
    <p style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Kova burcu erkeği nazik, iyimser, özgürlüğüne düşkün ve çok yönlü yapısıyla dikkati çeker. Çok yönlü oluşu zor anlaşılan bir kişilik sergilemesine neden olur. Duygularını kolay kolay belli etmez. Hoş ve neşeli kişiliği toplum içinde sevilen bir insan olmasını sağlar.<br />
        <br />
        Kova burcu erkeği pratik ve çalışkandır. Kendi işini yapmaktan çok keyif alır. Değişiklikten ve farklılıktan keyif alır. Hareketli yaşantısı onu mutlu ve enerjik kılar.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        <br />
        </font>
    </p>
</asp:Content>

