<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="Default.aspx.cs" Inherits="_Default" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <b style="color: rgb(242 ,242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255);"><font color="#27373f" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" size="2" style="color: rgb(242, 242 ,242); font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><b><br />
    <br />
    Olumlu Özellikleri:</b><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Keyifli. Neşeli, îş bilir. Açık zihinli. Adapte olur. İyi yargılar, Felsefik. Özgürlüğüne düşkün. Dışa dönük. Dindar. Eğitimli. Olgun. İyi niyetli. Sportmen. Yüksek hayal gücü. Şanslı. Neşeli.</font></font><p style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <b><font color="#27373f" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" size="2"><b>Olumsuz Özellikleri:</b><span class="Apple-converted-space">&nbsp;</span><font color="#ffffff">Aşırı iyimser. Gürültücü. Sorumsuz. Kaprisli. Ani ilgi. Çabuk bıkmak. Sabırsızlık</font></font></p>
    <p style="color: rgb(242, 242, 242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; ">
        <font face="Verdana" size="2"><b>Yay Takım Yıldızı (Astronomi)</b><span class="Apple-converted-space">&nbsp;</span>Y<font color="#ffffff">ay takımyıldızının birinci dekanatında Kyra-Harp yer alır. Lyra, Yay burcunun neşeli, şen, memnun ve mutlu yanını sembolize eder. Kuzey yarımkürenin en parlak yıldızı, Zafer anlamındaki Vega da Lyra&#39;nın içinde bulunur. Yay&#39;ın orta dekanatında Araplar tarafından Al Mugamra denilen Ara yer alır. Son dekanatta ise Al Waid, Thuban, Al Dib gibi başlıca yıldızları kapsayan Draco yani Canavar yıldız kümesi bulunur.</font></font></p>
    <b style="color: rgb(242 ,242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; "><font color="#ffffff" size="2"><span class="Apple-converted-space">&nbsp;</span></font></b><font face="Verdana" style="color: rgb(242 ,242 ,242); font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px; "><b><font color="#800000" size="2">Yay Burcu Kadını Genel Özellikleri</font></b></font><p style="color: rgb(0, 0, 0); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Yay burcu kadını kültürlü, alımlı, espritüel, duyarlı ve akıllı yönleriyle dikkat çeker. Hassas ve kırılgan bir yapısı vardır. Affedicidir. Zekidir ve kavrama yeteneği kuvvetlidir. Birden fazla konuya ilgi duyabilir ve hepsiyle ilgili bilgi sahibi olabilir.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Yay burcu kadınının sıkılgan ve çabuk bıkan bir yapısı vardır. Huzursuzluktan hoşlanmaz ve huzursuzluk olan ortamlarda fazla bulunmaz. Çevresinde enerjik ve neşeli yapısıyla aranan bir dosttur.Dostlarına çok önem verir ve fedakardır.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Yay burcu kadını eğlenceye ve gezmeye meraklıdır. Seyahat etmeyi, yeni yerler görmeyi ve yeni insanlarla tanışmayı sever. Maddi anlamda güçlü olmak ister. Para onun için araçtır.Cömert hatta biraz savurgandır.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        </font><font face="Verdana"><b><font color="#800000" size="2">Yay Burcu Erkeği Genel Özellikleri</font></b></font></p>
    <p style="color: rgb(242 ,242 ,242); font-family: 'Times New Roman'; font-size: medium; font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 1; word-spacing: 0px; -webkit-text-stroke-width: 0px;">
        <font color="#ffffff" face="Verdana" size="2">Yay burcu erkeği entelektüel, duyarlı, meraklı, neşeli ve cana yakın yapısıyla dikkat çeker.İyi niyetli ve konuşkandır. Dostlarına düşkündür ve arkadaş canlısıdır.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Hareketsizlik yay burcu erkeğini sıkar. O hep hareketli olmalı ve açık havada bulunmalıdır. Kapalı ortamlarda çok uzun süre kalmaktan hoşlanmaz.<span class="Apple-converted-space">&nbsp;</span><br />
        <br />
        Yay burcu erkeği birçok konuda bilgi . Bu da onun meraklı bir yapısı olmasından kaynaklanır. Eleştirmeyi sever ve açık sözlüdür. Bazen bu açık sözlülük pot kırma sınırını da aşabilmektedir.Cömertliğiyle tanınan yay burcu erkeği harcamalarında savurganlık sınırını fazlasıyla aşabilir.<span class="Apple-converted-space">&nbsp;</span><br />
        </font>
    </p>
</asp:Content>

